### ISSUE TITLE
Where's the Troubleshooting Section?

### ISSUE THREAD

**Issue by aramperez** [braincorp/brainos_wiki#1]
In at least two places there is mention of a Troubleshotting section but I can't find it. When I run the examples, all I see is green static.

The red LED comes on my camera.

Thanks,
Aram

**Comment by laurentbc** [comment]
Hi Aram,

We can confirm that BrainOS Beta 0.5.1 has this problem with Raspberry Pi cameras.  The issue has been fixed in the new 0.5.2 update that will be released in the next few days.  (The update will take just a few minutes to apply once it is released, through an apt-get command; or you can download a new 0.5.2 image.)

Thank you for bringing this issue to our attention.

Regards,
Patryk
